### ISSUE TITLE
descendantsOrSelfOf with leaf concepts

### ISSUE THREAD

**Issue by danka74** [slaverman/SnoLyze#1]
descendantOrSelfOf first checks if there are any entries in transitiveclosure with supertypeId = sctid. If sctid is a leaf concept the result will be empty and an empty vector will be returned instead of the vector of only sctid. Two options: assume sctid exists and return singleton vector OR run (costly) check of transitiveclosure[subtypeId == sctid] to verify correctness of sctid.

**Comment by slaverman** [comment]
A third option; to check if sctid is a sourceId in the isa table
`if(sctid %in% isa$sourceId)
      {
        return(sctid)
      }
      else
      {
        return(emptyVector())
      }`
I will benchmark all the methods tomorrow and update it immediately after the benchmarks.

Update: an additional table in memory with all sctids and with indices on sctid is only 2.3 Mb and a quick look up table to check if a scitd exists. This will also boost any query with "*" significantly.

**Comment by danka74** [comment]
I think the latter would be the preferred solution, use some memory to gain speed!

**Comment by slaverman** [comment]
Fixed in version 1.1
