### ISSUE TITLE
Relationship grouping seems incorrect

### ISSUE THREAD

**Issue by ronaldcornet** [slaverman/SnoLyze#3]
The idea of relationship grouping is to ensure that attributes belong together. Prototypical example is 86299006 | Tetralogy of Fallot (disorder) |
This has 5 groups with finding site and morphology.
One group contains: right ventricle + hypertrophy
Another group: thoracic aorta + overriding

So, there is no combination "thoracic aorta + hypertrophy".
So, querying for a group with this combi shouldn't return Fallot.

However, these two queries (with and without { } for grouping) return the same set of concepts, all subtypes of (and including) Fallot.
execute("<<  404684003 |Clinical finding| : { 363698007 | Finding site (attribute) | = << 113262008 | Thoracic aorta structure (body structure) | } , { 116676008 | Associated morphology (attribute) | = << 56246009 | Hypertrophy (morphologic abnormality) | } ")
returns 7 concepts

execute("<<  404684003 |Clinical finding| : 363698007 | Finding site (attribute) | = << 113262008 | Thoracic aorta structure (body structure) | , 116676008 | Associated morphology (attribute) | = << 56246009 | Hypertrophy (morphologic abnormality) | ")
returns 7 concepts

The first one shouldn't return these, for the second one that's correct.

This seems to relate to https://github.com/slaverman/SnoLyze/blob/master/R/eclFunctions.R line 165.

**Comment by slaverman** [comment]
> << 404684003 |Clinical finding| : **{ 363698007 | Finding site (attribute) | = << 113262008 | Thoracic aorta structure (body structure) | }** , _{ 116676008 | Associated morphology (attribute) | = << 56246009 | Hypertrophy (morphologic abnormality) | }_
 
The attributes are not grouped together in the example above here. The attributes are grouped separately (see bold and italic highlighted parts).

I think you meant an example like below here, where the attributes are grouped together:

> << 404684003 |Clinical finding| : { 363698007 | Finding site (attribute) | = << 113262008 | Thoracic aorta structure (body structure) |  , 116676008 | Associated morphology (attribute) | = << 56246009 | Hypertrophy (morphologic abnormality) | }

Then you are right that 86299006 | Tetralogy of Fallot (disorder) | is not a valid result. This is now fixed in SnoLyze 1.2. Thank you for pointing it out!
