### ISSUE TITLE
Proposed solution for : fread fails in launch --> readRel. 

### ISSUE THREAD

**Issue by ronaldcornet** [slaverman/SnoLyze#6]
It seems that fread doesn't work anymore in readRel.

I suggest this new readRel function (first 3 lines removed, then 2 added , and a conversion to data.table before setkey:

readRel <- function(source)
{
  \# rel_cols <- list(logical = "active", character = c("sourceId","destinationId","typeId","characteristicTypeId"),  numeric = "relationshipGroup")
  \# rel_drop <- c("effectiveTime","id","moduleId","modifierId")
  \# rel <- fread(source, colClasses = rel_cols, drop = rel_drop, showProgress = FALSE)
  rel <- read.table(source, header = TRUE, sep ="\t", numerals = "no.loss")
  rel <- rel[,c("active", "sourceId", "destinationId", "typeId", "characteristicTypeId", "relationshipGroup")]

  rel$sourceId <- as.integer64(rel$sourceId)
  rel$typeId <- as.integer64(rel$typeId)
  rel$destinationId <- as.integer64(rel$destinationId)
  rel$characteristicTypeId <- as.integer64(rel$characteristicTypeId)

  rel <- as.data.table(rel)

  setkey(rel, typeId)
  return(rel)
}

**Comment by slaverman** [comment]
See my latest commit, [https://github.com/slaverman/SnoLyze/commit/d591b47265cd1c27b8e383ab21b85aa42cc2bf00](url)

Can you confirm that this fixed your problem?

**Comment by ronaldcornet** [comment]
Works like a charm, Sander!

Thanks for fixing.

Best regards, Ronald
 [cid:image002.png@01D40E30.3E299A80]
[image004]

Ronald Cornet, PhD | Associate professor
Medical Informatics
Amsterdam Public Health Research Institute
Location AMC | J1b-115 | Meibergdreef 15, 1105 AZ  Amsterdam
T: +31 20 566 5188 | E: r.cornet@amc.uva.nl<mailto:r.cornet@amc.uva.nl> | https://kik.amc.nl/home/rcornet
www.amsterdamumc.nl<http://www.amsterdamumc.nl/> | www.amc.nl<http://www.amc.nl/>

**Comment by vojtechhuser** [comment]
this can be closed now

**Comment by slaverman** [comment]
Glad to hear!
