### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vojtechhuser** [slaverman/SnoLyze#7]
I am not able to use the package.
R  always crashes.

Readme should describe what strategy the package is using.
btw. I have a similar R script here R4SNOMEDCT https://github.com/lhncbc/r-snippets-bmi/tree/master/R4SNOMEDCT

```R
#devtools::install_github("slaverman/SnoLyze")
library(SnoLyze)
transitive <- getTransitiveClosure()
rfile<-"n:/snomed/SnomedCT_InternationalRF2_PRODUCTION_20180131T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20180131.txt"
launch(rfile)

library(data.table)
SnoLyze:::readRel(rfile)
```

**Comment by slaverman** [comment]
See my latest commit, [https://github.com/slaverman/SnoLyze/commit/d591b47265cd1c27b8e383ab21b85aa42cc2bf00](url)

Can you confirm that this fixed your problem?

**Comment by vojtechhuser** [comment]
I am able to read the file like this

rfile<-"n:/snomed/SnomedCT_InternationalRF2_PRODUCTION_20180131T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20180131.txt"
rels<-SnoLyze:::readRel(rfile)


but the other
launch(rfile)


fails


![image](https://user-images.githubusercontent.com/7526119/47451554-17d98e00-d796-11e8-95ee-0eb99a135cdf.png)

**Comment by slaverman** [comment]
I'm not able to reproduce your problem. Please try the code below with an empty environment. This worked for me with the latest R release (3.5.1 x64).
```r
remove.packages("SnoLyze")
devtools::install_github("slaverman/SnoLyze")
SnoLyze::launch("PATH_TO_SNOMED_CT_SNAPSHOT_RELATIONSHIP_FILE")
```

**Comment by vojtechhuser** [comment]
hmm... after remove.package it worked. Strange. Previously install_github nicely replaced it (with other packages).
